package:
  name: "qnt"
  version: "0.0.302"

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
  - pip
  - python >=3.10,<3.11
  - setuptools

  run:
    - scipy>=1.11.3
#    - pandas==1.2.5
    - xarray==0.20.2
    - bottleneck>=1.3.7
    - numpy==1.23.5
    - numba==0.58.1
    - tabulate>=0.8.3
    - python>=3.10,<3.11
    - progressbar2>=3.55,<4
  #  - conda-forge::dash=2.7.*
  #  - conda-forge::python-avro=1.8.*
  #  - conda-forge::ta-lib
  #  - conda-forge::dash

about:
  license: MIT
  home: https://quantnet.ai